services:
  - type: web
    name: task-manager-api
    runtime: docker
    repo: https://github.com/berserk3142-max/REST-API-for-a-Task-Management-system
    branch: main
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: API_KEY
        value: taskmanager-secret-api-key-2024
      - key: API_SECURITY_ENABLED
        value: false
